/* 
 * Copyright 2022 Patrik Karlström.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.jota.client.ui_swing.editor.module.job;

import java.io.File;
import se.trixon.jota.shared.job.Job;
import se.trixon.jota.shared.job.JobExecuteSection;
import se.trixon.almond.util.Dict;
import se.trixon.almond.util.swing.dialogs.FileChooserPanel;

/**
 *
 * @author Patrik Karlström
 */
public class JobExecutePanel extends JobModule implements FileChooserPanel.FileChooserButtonListener {

    /**
     * Creates new form JobExecute
     */
    public JobExecutePanel() {
        initComponents();
        init();
    }

    @Override
    public void loadJob(Job job) {
        JobExecuteSection executeSection = job.getExecuteSection();

        beforeHaltOnErrorCheckBox.setEnabled(executeSection.isBefore());
        beforeHaltOnErrorCheckBox.setSelected(executeSection.isBeforeHaltOnError());

        beforePanel.setSelected(executeSection.isBefore());
        beforePanel.setPath(executeSection.getBeforeCommand());
        beforePanel.setEnabled(beforePanel.isSelected());

        afterFailurePanel.setSelected(executeSection.isAfterFailure());
        afterFailurePanel.setPath(executeSection.getAfterFailureCommand());
        afterFailurePanel.setEnabled(afterFailurePanel.isSelected());

        afterSuccessPanel.setSelected(executeSection.isAfterSuccess());
        afterSuccessPanel.setPath(executeSection.getAfterSuccessCommand());
        afterSuccessPanel.setEnabled(afterSuccessPanel.isSelected());

        afterPanel.setSelected(executeSection.isAfter());
        afterPanel.setPath(executeSection.getAfterCommand());
        afterPanel.setEnabled(afterPanel.isSelected());
    }

    @Override
    public Job saveJob(Job job) {
        JobExecuteSection executeSection = job.getExecuteSection();
        executeSection.setBefore(beforePanel.isSelected());
        executeSection.setBeforeCommand(beforePanel.getPath());
        executeSection.setBeforeHaltOnError(beforeHaltOnErrorCheckBox.isSelected());

        executeSection.setAfterFailure(afterFailurePanel.isSelected());
        executeSection.setAfterFailureCommand(afterFailurePanel.getPath());

        executeSection.setAfterSuccess(afterSuccessPanel.isSelected());
        executeSection.setAfterSuccessCommand(afterSuccessPanel.getPath());

        executeSection.setAfter(afterPanel.isSelected());
        executeSection.setAfterCommand(afterPanel.getPath());

        return job;
    }

    @Override
    public void onFileChooserCancel(FileChooserPanel fileChooserPanel) {
    }

    @Override
    public void onFileChooserCheckBoxChange(FileChooserPanel fileChooserPanel, boolean isSelected) {
        if (fileChooserPanel == beforePanel) {
            beforeHaltOnErrorCheckBox.setEnabled(isSelected);
        }
    }

    @Override
    public void onFileChooserDrop(FileChooserPanel fileChooserPanel) {
    }

    @Override
    public void onFileChooserOk(FileChooserPanel fileChooserPanel, File file) {
    }

    @Override
    public void onFileChooserPreSelect(FileChooserPanel fileChooserPanel) {
    }

    private void init() {
        mTitle = Dict.RUN.toString();
        beforePanel.setButtonListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        beforePanel = new se.trixon.almond.util.swing.dialogs.FileChooserPanel();
        beforeHaltOnErrorCheckBox = new javax.swing.JCheckBox();
        afterFailurePanel = new se.trixon.almond.util.swing.dialogs.FileChooserPanel();
        afterSuccessPanel = new se.trixon.almond.util.swing.dialogs.FileChooserPanel();
        afterPanel = new se.trixon.almond.util.swing.dialogs.FileChooserPanel();

        beforePanel.setCheckBoxMode(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("se/trixon/jota/client/ui_swing/editor/module/job/Bundle"); // NOI18N
        beforePanel.setHeader(bundle.getString("JobPanel.beforePanel.header")); // NOI18N

        beforeHaltOnErrorCheckBox.setText(Dict.STOP_ON_ERROR.toString());

        afterFailurePanel.setCheckBoxMode(true);
        afterFailurePanel.setHeader(bundle.getString("JobPanel.afterFailurePanel.header")); // NOI18N

        afterSuccessPanel.setCheckBoxMode(true);
        afterSuccessPanel.setHeader(bundle.getString("JobPanel.afterSuccessPanel.header")); // NOI18N

        afterPanel.setCheckBoxMode(true);
        afterPanel.setHeader(bundle.getString("JobPanel.afterPanel.header")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(beforePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(beforeHaltOnErrorCheckBox)
                        .addGap(0, 276, Short.MAX_VALUE))
                    .addComponent(afterSuccessPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(afterFailurePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(afterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(beforePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beforeHaltOnErrorCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterFailurePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(afterSuccessPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(afterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private se.trixon.almond.util.swing.dialogs.FileChooserPanel afterFailurePanel;
    private se.trixon.almond.util.swing.dialogs.FileChooserPanel afterPanel;
    private se.trixon.almond.util.swing.dialogs.FileChooserPanel afterSuccessPanel;
    private javax.swing.JCheckBox beforeHaltOnErrorCheckBox;
    private se.trixon.almond.util.swing.dialogs.FileChooserPanel beforePanel;
    // End of variables declaration//GEN-END:variables
}
