/* 
 * Copyright 2015 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.jotaclient.ui.editor.task_modules;

import se.trixon.jota.task.Task;
import se.trixon.util.dictionary.Dict;
import java.io.File;
import se.trixon.util.swing.dialogs.FileChooserPanel;

/**
 *
 * @author Patrik Karlsson
 */
public class ModuleExecutePanel extends ModulePanel implements FileChooserPanel.FileChooserButtonListener {

    /**
     * Creates new form ModulePanel
     */
    public ModuleExecutePanel() {
        initComponents();
        init();
    }

    @Override
    public void loadTask(Task task) {
        postExecutePanel.setPath(task.getPostExecuteCommand());
        runBeforePanel.setPath(task.getRunBeforeCommand());

        postExecuteOnErrorCheckBox.setSelected(task.isPostOnError());
        postExecutePanel.setSelected(task.isPostExecute());
        runBeforeHaltOnErrorCheckBox.setSelected(task.isRunBeforeHaltOnError());
        runBeforePanel.setSelected(task.isRunBefore());
        runBeforePanel.setEnabled(runBeforePanel.isSelected());

        postExecuteOnErrorCheckBox.setEnabled(task.isPostExecute());
        runBeforeHaltOnErrorCheckBox.setEnabled(task.isRunBefore());
    }

    @Override
    public void onFileChooserCancel(FileChooserPanel fileChooserPanel) {
    }

    @Override
    public void onFileChooserCheckBoxChange(FileChooserPanel fileChooserPanel, boolean isSelected) {
        if (fileChooserPanel == runBeforePanel) {
            runBeforeHaltOnErrorCheckBox.setEnabled(isSelected);
        } else if (fileChooserPanel == postExecutePanel) {
            postExecuteOnErrorCheckBox.setEnabled(isSelected);
        }
    }

    @Override
    public void onFileChooserDrop(FileChooserPanel fileChooserPanel) {
    }

    @Override
    public void onFileChooserOk(FileChooserPanel fileChooserPanel, File file) {
    }

    @Override
    public void onFileChooserPreSelect(FileChooserPanel fileChooserPanel) {
    }

    @Override
    public Task saveTask(Task task) {
        task.setPostExecuteCommand(postExecutePanel.getPath());
        task.setRunBeforeCommand(runBeforePanel.getPath());
        task.setPostExecute(postExecutePanel.isSelected());
        task.setPostOnError(postExecuteOnErrorCheckBox.isSelected());
        task.setRunBefore(runBeforePanel.isSelected());
        task.setRunBeforeHaltOnError(runBeforeHaltOnErrorCheckBox.isSelected());

        return task;
    }

    private void init() {
        mTitle = Dict.RUN.getString();

        runBeforePanel.setButtonListener(this);
        runBeforePanel.setCheckBoxMode(true);
        runBeforePanel.setEnabled(false);
        //preExecutePanel.setHeader(NbBundle.getMessage(ModuleExecutePanel.class, "ModuleExecutePanel.preExecute.text")); // NOI18N

        postExecutePanel.setButtonListener(this);
        postExecutePanel.setCheckBoxMode(true);
        postExecutePanel.setEnabled(false);
        //postExecutePanel.setHeader(NbBundle.getMessage(ModuleExecutePanel.class, "ModuleExecutePanel.postExecute.text")); // NOI18N
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prePostScrollPane = new javax.swing.JScrollPane();
        prePostPanel = new javax.swing.JPanel();
        runBeforeHaltOnErrorCheckBox = new javax.swing.JCheckBox();
        runBeforePanel = new se.trixon.util.swing.dialogs.FileChooserPanel();
        postExecutePanel = new se.trixon.util.swing.dialogs.FileChooserPanel();
        postExecuteOnErrorCheckBox = new javax.swing.JCheckBox();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        prePostPanel.setBorder(null);

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("se/trixon/jotaclient/ui/editor/task_modules/Bundle"); // NOI18N
        runBeforeHaltOnErrorCheckBox.setText(bundle.getString("ModuleExecutePanel.runBeforeHaltOnErrorCheckBox.text")); // NOI18N

        runBeforePanel.setHeader(bundle.getString("ModuleExecutePanel.preExecute.text")); // NOI18N

        postExecutePanel.setHeader(bundle.getString("ModuleExecutePanel.postExecute.text")); // NOI18N

        postExecuteOnErrorCheckBox.setText(bundle.getString("ModuleExecutePanel.postExecuteOnErrorCheckBox.text")); // NOI18N

        javax.swing.GroupLayout prePostPanelLayout = new javax.swing.GroupLayout(prePostPanel);
        prePostPanel.setLayout(prePostPanelLayout);
        prePostPanelLayout.setHorizontalGroup(
            prePostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(runBeforePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(postExecutePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(prePostPanelLayout.createSequentialGroup()
                .addGroup(prePostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(runBeforeHaltOnErrorCheckBox)
                    .addComponent(postExecuteOnErrorCheckBox))
                .addContainerGap())
        );
        prePostPanelLayout.setVerticalGroup(
            prePostPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prePostPanelLayout.createSequentialGroup()
                .addComponent(runBeforePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runBeforeHaltOnErrorCheckBox)
                .addGap(18, 18, 18)
                .addComponent(postExecutePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postExecuteOnErrorCheckBox)
                .addContainerGap())
        );

        prePostScrollPane.setViewportView(prePostPanel);

        add(prePostScrollPane);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox postExecuteOnErrorCheckBox;
    private se.trixon.util.swing.dialogs.FileChooserPanel postExecutePanel;
    private javax.swing.JPanel prePostPanel;
    private javax.swing.JScrollPane prePostScrollPane;
    private javax.swing.JCheckBox runBeforeHaltOnErrorCheckBox;
    private se.trixon.util.swing.dialogs.FileChooserPanel runBeforePanel;
    // End of variables declaration//GEN-END:variables
}
