/* 
 * Copyright 2016 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.jotaclient.ui.editor.task_modules;

import se.trixon.jota.task.Task;
import se.trixon.util.dictionary.Dict;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
public class ModuleExcludePanel extends ModulePanel {

    /**
     * Creates new form ModulePanel
     */
    public ModuleExcludePanel() {
        initComponents();
        init();
    }

    @Override
    public void loadTask(Task task) {
        backupCheckBox.setSelected(task.isExcludeTemplateBackup());
        cacheCheckBox.setSelected(task.isExcludeTemplateCache());
        gvfsCheckBox.setSelected(task.isExcludeTemplateGvfs());
        lostFoundCheckBox.setSelected(task.isExcludeTemplateLostFound());
        sysDirsCheckBox.setSelected(task.isExcludeTemplateSystemDirs());
        sysMountsCheckBox.setSelected(task.isExcludeTemplateSystemMountDirs());
        tempCheckBox.setSelected(task.isExcludeTemplateTemp());
        trashCheckBox.setSelected(task.isExcludeTemplateTrash());
    }

    @Override
    public Task saveTask(Task task) {
        task.setExcludeTemplateBackup(backupCheckBox.isSelected());
        task.setExcludeTemplateCache(cacheCheckBox.isSelected());
        task.setExcludeTemplateGvfs(gvfsCheckBox.isSelected());
        task.setExcludeTemplateLostFound(lostFoundCheckBox.isSelected());
        task.setExcludeTemplateSystemDirs(sysDirsCheckBox.isSelected());
        task.setExcludeTemplateSystemMountDirs(sysMountsCheckBox.isSelected());
        task.setExcludeTemplateTemp(tempCheckBox.isSelected());
        task.setExcludeTemplateTrash(trashCheckBox.isSelected());

        return task;
    }

    private void init() {
        mTitle = Dict.EXCLUDE.getString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        templatePanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        tempCheckBox = new javax.swing.JCheckBox();
        backupCheckBox = new javax.swing.JCheckBox();
        cacheCheckBox = new javax.swing.JCheckBox();
        trashCheckBox = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        sysMountsCheckBox = new javax.swing.JCheckBox();
        sysDirsCheckBox = new javax.swing.JCheckBox();
        lostFoundCheckBox = new javax.swing.JCheckBox();
        gvfsCheckBox = new javax.swing.JCheckBox();

        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.PAGE_AXIS));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("se/trixon/jotaclient/ui/editor/task_modules/Bundle"); // NOI18N
        templatePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ModuleExcludePanel.templatePanel.border.title"))); // NOI18N
        templatePanel.setLayout(new java.awt.GridLayout(1, 2));

        tempCheckBox.setText(bundle.getString("ModuleExcludePanel.tempCheckBox.text")); // NOI18N

        backupCheckBox.setText(bundle.getString("ModuleExcludePanel.backupCheckBox.text")); // NOI18N

        cacheCheckBox.setText(bundle.getString("ModuleExcludePanel.cacheCheckBox.text")); // NOI18N

        trashCheckBox.setText(bundle.getString("ModuleExcludePanel.trashCheckBox.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trashCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backupCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tempCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cacheCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tempCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backupCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cacheCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trashCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        templatePanel.add(jPanel3);

        sysMountsCheckBox.setText(bundle.getString("ModuleExcludePanel.sysMountsCheckBox.text")); // NOI18N

        sysDirsCheckBox.setText(bundle.getString("ModuleExcludePanel.sysDirsCheckBox.text")); // NOI18N

        lostFoundCheckBox.setText(bundle.getString("ModuleExcludePanel.lostFoundCheckBox.text")); // NOI18N

        gvfsCheckBox.setText(bundle.getString("ModuleExcludePanel.gvfsCheckBox.text")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sysMountsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sysDirsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lostFoundCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(gvfsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(sysMountsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sysDirsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lostFoundCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gvfsCheckBox)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        templatePanel.add(jPanel4);

        panel.add(templatePanel);

        scrollPane.setViewportView(panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox backupCheckBox;
    private javax.swing.JCheckBox cacheCheckBox;
    private javax.swing.JCheckBox gvfsCheckBox;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox lostFoundCheckBox;
    private javax.swing.JPanel panel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JCheckBox sysDirsCheckBox;
    private javax.swing.JCheckBox sysMountsCheckBox;
    private javax.swing.JCheckBox tempCheckBox;
    private javax.swing.JPanel templatePanel;
    private javax.swing.JCheckBox trashCheckBox;
    // End of variables declaration//GEN-END:variables
}
