/* 
 * Copyright 2015 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.jotaclient.ui.editor.task_modules;

import se.trixon.jota.task.Task;
import se.trixon.util.dictionary.Dict;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
public class ModuleOptionsPanel extends ModulePanel {

    /**
     * Creates new form ModulePanel
     */
    public ModuleOptionsPanel() {
        initComponents();
        init();
    }

    @Override
    public void loadTask(Task task) {
        additionalOptionsTextArea.setText(task.getAdditionalOptions());

        backupCheckBox.setSelected(task.isBackup());
        checksumCheckBox.setSelected(task.isChecksum());
        compressCheckBox.setSelected(task.isCompress());
        deleteCheckBox.setSelected(task.isDelete());
        devicesCheckBox.setSelected(task.isDevices());
        dirsCheckBox.setSelected(task.isDirs());
        existingCheckBox.setSelected(task.isExisting());
        groupCheckBox.setSelected(task.isGroup());
        hardlinksCheckBox.setSelected(task.isHardLinks());
        ignoreExistingCheckBox.setSelected(task.isIgnoreExisting());
        itemizeChangesCheckBox.setSelected(task.isItemizeChanges());
        linksCheckBox.setSelected(task.isLinks());
        modifyWindowCheckBox.setSelected(task.isModifyWindow());
        numericIdsCheckBox.setSelected(task.isNumericIds());
        oneFileSystemCheckBox.setSelected(task.isOneFileSystem());
        ownerCheckBox.setSelected(task.isOwner());
        partialProgressCheckBox.setSelected(task.isPartialProgress());
        permsCheckBox.setSelected(task.isPerms());
        progressCheckBox.setSelected(task.isProgress());
        sizeOnlyCheckBox.setSelected(task.isSizeOnly());
        updateCheckBox.setSelected(task.isUpdate());
        verboseCheckBox.setSelected(task.isVerbose());
    }

    @Override
    public Task saveTask(Task task) {
        task.setAdditionalOptions(additionalOptionsTextArea.getText());
        task.setBackup(backupCheckBox.isSelected());
        task.setChecksum(checksumCheckBox.isSelected());
        task.setCompress(compressCheckBox.isSelected());
        task.setDelete(deleteCheckBox.isSelected());
        task.setDevices(devicesCheckBox.isSelected());
        task.setDirs(dirsCheckBox.isSelected());
        task.setExisting(existingCheckBox.isSelected());
        task.setGroup(groupCheckBox.isSelected());
        task.setHardLinks(hardlinksCheckBox.isSelected());
        task.setIgnoreExisting(ignoreExistingCheckBox.isSelected());
        task.setItemizeChanges(itemizeChangesCheckBox.isSelected());
        task.setLinks(linksCheckBox.isSelected());
        task.setModifyWindow(modifyWindowCheckBox.isSelected());
        task.setNumericIds(numericIdsCheckBox.isSelected());
        task.setOneFileSystem(oneFileSystemCheckBox.isSelected());
        task.setOwner(ownerCheckBox.isSelected());
        task.setPartialProgress(partialProgressCheckBox.isSelected());
        task.setPerms(permsCheckBox.isSelected());
        task.setProgress(progressCheckBox.isSelected());
        task.setProtectArgs(protectArgsCheckBox.isSelected());
        task.setSizeOnly(sizeOnlyCheckBox.isSelected());
        task.setTimes(timesCheckBox.isSelected());
        task.setUpdate(updateCheckBox.isSelected());
        task.setVerbose(verboseCheckBox.isSelected());

        return task;
    }

    private void init() {
        mTitle = Dict.OPTIONS.getString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        basicPanel = new javax.swing.JPanel();
        basic1Panel = new javax.swing.JPanel();
        basic11Panel = new javax.swing.JPanel();
        timesCheckBox = new javax.swing.JCheckBox();
        ownerCheckBox = new javax.swing.JCheckBox();
        basic12Panel = new javax.swing.JPanel();
        permsCheckBox = new javax.swing.JCheckBox();
        groupCheckBox = new javax.swing.JCheckBox();
        basicSeparator = new javax.swing.JSeparator();
        basic2Panel = new javax.swing.JPanel();
        basic21Panel = new javax.swing.JPanel();
        verboseCheckBox = new javax.swing.JCheckBox();
        ignoreExistingCheckBox = new javax.swing.JCheckBox();
        updateCheckBox = new javax.swing.JCheckBox();
        deleteCheckBox = new javax.swing.JCheckBox();
        basic22Panel = new javax.swing.JPanel();
        oneFileSystemCheckBox = new javax.swing.JCheckBox();
        progressCheckBox = new javax.swing.JCheckBox();
        sizeOnlyCheckBox = new javax.swing.JCheckBox();
        modifyWindowCheckBox = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        advanced1Panel = new javax.swing.JPanel();
        advanced11Panel = new javax.swing.JPanel();
        checksumCheckBox = new javax.swing.JCheckBox();
        devicesCheckBox = new javax.swing.JCheckBox();
        partialProgressCheckBox = new javax.swing.JCheckBox();
        linksCheckBox = new javax.swing.JCheckBox();
        backupCheckBox = new javax.swing.JCheckBox();
        dirsCheckBox = new javax.swing.JCheckBox();
        advanced12Panel = new javax.swing.JPanel();
        compressCheckBox = new javax.swing.JCheckBox();
        existingCheckBox = new javax.swing.JCheckBox();
        numericIdsCheckBox = new javax.swing.JCheckBox();
        hardlinksCheckBox = new javax.swing.JCheckBox();
        itemizeChangesCheckBox = new javax.swing.JCheckBox();
        protectArgsCheckBox = new javax.swing.JCheckBox();
        additionalScrollPane = new javax.swing.JScrollPane();
        additionalOptionsTextArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        panel.setAlignmentX(0.5F);
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.PAGE_AXIS));

        basic1Panel.setLayout(new java.awt.GridLayout(1, 0));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("se/trixon/editor/task_modules/Bundle"); // NOI18N
        timesCheckBox.setText(bundle.getString("ModuleOptionsPanel.timesCheckBox.text")); // NOI18N
        timesCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.timesCheckBox.toolTipText")); // NOI18N

        ownerCheckBox.setText(bundle.getString("ModuleOptionsPanel.ownerCheckBox.text")); // NOI18N
        ownerCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.ownerCheckBox.toolTipText")); // NOI18N

        javax.swing.GroupLayout basic11PanelLayout = new javax.swing.GroupLayout(basic11Panel);
        basic11Panel.setLayout(basic11PanelLayout);
        basic11PanelLayout.setHorizontalGroup(
            basic11PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic11PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basic11PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(timesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ownerCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        basic11PanelLayout.setVerticalGroup(
            basic11PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic11PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(timesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ownerCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        basic1Panel.add(basic11Panel);

        permsCheckBox.setText(bundle.getString("ModuleOptionsPanel.permsCheckBox.text")); // NOI18N
        permsCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.permsCheckBox.toolTipText")); // NOI18N

        groupCheckBox.setText(bundle.getString("ModuleOptionsPanel.groupCheckBox.text")); // NOI18N
        groupCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.groupCheckBox.toolTipText")); // NOI18N

        javax.swing.GroupLayout basic12PanelLayout = new javax.swing.GroupLayout(basic12Panel);
        basic12Panel.setLayout(basic12PanelLayout);
        basic12PanelLayout.setHorizontalGroup(
            basic12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic12PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basic12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(permsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(groupCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        basic12PanelLayout.setVerticalGroup(
            basic12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic12PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(permsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(groupCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        basic1Panel.add(basic12Panel);

        basic2Panel.setLayout(new java.awt.GridLayout(1, 0));

        verboseCheckBox.setText(bundle.getString("ModuleOptionsPanel.verboseCheckBox.text")); // NOI18N
        verboseCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.verboseCheckBox.toolTipText")); // NOI18N

        ignoreExistingCheckBox.setText(bundle.getString("ModuleOptionsPanel.ignoreExistingCheckBox.text")); // NOI18N
        ignoreExistingCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.ignoreExistingCheckBox.toolTipText")); // NOI18N

        updateCheckBox.setText(bundle.getString("ModuleOptionsPanel.updateCheckBox.text")); // NOI18N
        updateCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.updateCheckBox.toolTipText")); // NOI18N

        deleteCheckBox.setText(bundle.getString("ModuleOptionsPanel.deleteCheckBox.text")); // NOI18N
        deleteCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.deleteCheckBox.toolTipText")); // NOI18N

        javax.swing.GroupLayout basic21PanelLayout = new javax.swing.GroupLayout(basic21Panel);
        basic21Panel.setLayout(basic21PanelLayout);
        basic21PanelLayout.setHorizontalGroup(
            basic21PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic21PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basic21PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verboseCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ignoreExistingCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        basic21PanelLayout.setVerticalGroup(
            basic21PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic21PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deleteCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verboseCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ignoreExistingCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        basic2Panel.add(basic21Panel);

        oneFileSystemCheckBox.setText(bundle.getString("ModuleOptionsPanel.oneFileSystemCheckBox.text")); // NOI18N
        oneFileSystemCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.oneFileSystemCheckBox.toolTipText")); // NOI18N

        progressCheckBox.setText(bundle.getString("ModuleOptionsPanel.progressCheckBox.text")); // NOI18N
        progressCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.progressCheckBox.toolTipText")); // NOI18N

        sizeOnlyCheckBox.setText(bundle.getString("ModuleOptionsPanel.sizeOnlyCheckBox.text")); // NOI18N
        sizeOnlyCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.sizeOnlyCheckBox.toolTipText")); // NOI18N

        modifyWindowCheckBox.setText(bundle.getString("ModuleOptionsPanel.modifyWindowCheckBox.text")); // NOI18N
        modifyWindowCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.modifyWindowCheckBox.toolTipText")); // NOI18N

        javax.swing.GroupLayout basic22PanelLayout = new javax.swing.GroupLayout(basic22Panel);
        basic22Panel.setLayout(basic22PanelLayout);
        basic22PanelLayout.setHorizontalGroup(
            basic22PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic22PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(basic22PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oneFileSystemCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sizeOnlyCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifyWindowCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        basic22PanelLayout.setVerticalGroup(
            basic22PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(basic22PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(oneFileSystemCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sizeOnlyCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyWindowCheckBox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        basic2Panel.add(basic22Panel);

        javax.swing.GroupLayout basicPanelLayout = new javax.swing.GroupLayout(basicPanel);
        basicPanel.setLayout(basicPanelLayout);
        basicPanelLayout.setHorizontalGroup(
            basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, basicPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(basicSeparator)
                        .addComponent(basic1Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(basic2Panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE))
                    .addContainerGap()))
        );
        basicPanelLayout.setVerticalGroup(
            basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 264, Short.MAX_VALUE)
            .addGroup(basicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(basicPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(basic1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(basicSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(basic2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel.add(basicPanel);

        advanced1Panel.setLayout(new java.awt.GridLayout(1, 0));

        checksumCheckBox.setText(bundle.getString("ModuleOptionsPanel.checksumCheckBox.text")); // NOI18N
        checksumCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.checksumCheckBox.toolTipText")); // NOI18N

        devicesCheckBox.setText(bundle.getString("ModuleOptionsPanel.devicesCheckBox.text")); // NOI18N
        devicesCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.devicesCheckBox.toolTipText")); // NOI18N

        partialProgressCheckBox.setText(bundle.getString("ModuleOptionsPanel.partialProgressCheckBox.text")); // NOI18N
        partialProgressCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.partialProgressCheckBox.toolTipText")); // NOI18N

        linksCheckBox.setText(bundle.getString("ModuleOptionsPanel.linksCheckBox.text")); // NOI18N
        linksCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.linksCheckBox.toolTipText")); // NOI18N

        backupCheckBox.setText(bundle.getString("ModuleOptionsPanel.backupCheckBox.text")); // NOI18N
        backupCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.backupCheckBox.toolTipText")); // NOI18N

        dirsCheckBox.setText(bundle.getString("ModuleOptionsPanel.dirsCheckBox.text")); // NOI18N
        dirsCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.dirsCheckBox.toolTipText")); // NOI18N

        javax.swing.GroupLayout advanced11PanelLayout = new javax.swing.GroupLayout(advanced11Panel);
        advanced11Panel.setLayout(advanced11PanelLayout);
        advanced11PanelLayout.setHorizontalGroup(
            advanced11PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advanced11PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advanced11PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checksumCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(devicesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(partialProgressCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(linksCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backupCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dirsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        advanced11PanelLayout.setVerticalGroup(
            advanced11PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advanced11PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checksumCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(devicesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(partialProgressCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linksCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backupCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dirsCheckBox)
                .addGap(0, 0, 0))
        );

        advanced1Panel.add(advanced11Panel);

        compressCheckBox.setText(bundle.getString("ModuleOptionsPanel.compressCheckBox.text")); // NOI18N
        compressCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.compressCheckBox.toolTipText")); // NOI18N

        existingCheckBox.setText(bundle.getString("ModuleOptionsPanel.existingCheckBox.text")); // NOI18N
        existingCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.existingCheckBox.toolTipText")); // NOI18N

        numericIdsCheckBox.setText(bundle.getString("ModuleOptionsPanel.numericIdsCheckBox.text")); // NOI18N
        numericIdsCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.numericIdsCheckBox.toolTipText")); // NOI18N

        hardlinksCheckBox.setText(bundle.getString("ModuleOptionsPanel.hardlinksCheckBox.text")); // NOI18N
        hardlinksCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.hardlinksCheckBox.toolTipText")); // NOI18N

        itemizeChangesCheckBox.setText(bundle.getString("ModuleOptionsPanel.itemizeChangesCheckBox.text")); // NOI18N
        itemizeChangesCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.itemizeChangesCheckBox.toolTipText")); // NOI18N

        protectArgsCheckBox.setText(bundle.getString("ModuleOptionsPanel.protectArgsCheckBox.text")); // NOI18N
        protectArgsCheckBox.setToolTipText(bundle.getString("ModuleOptionsPanel.protectArgsCheckBox.toolTipText")); // NOI18N

        javax.swing.GroupLayout advanced12PanelLayout = new javax.swing.GroupLayout(advanced12Panel);
        advanced12Panel.setLayout(advanced12PanelLayout);
        advanced12PanelLayout.setHorizontalGroup(
            advanced12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advanced12PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(advanced12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(compressCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(existingCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numericIdsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hardlinksCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(itemizeChangesCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(protectArgsCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        advanced12PanelLayout.setVerticalGroup(
            advanced12PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advanced12PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(compressCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(existingCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numericIdsCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hardlinksCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itemizeChangesCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(protectArgsCheckBox)
                .addContainerGap())
        );

        advanced1Panel.add(advanced12Panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(advanced1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(advanced1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panel.add(jPanel1);

        additionalScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("ModuleOptionsPanel.additionalScrollPane.border.title"))); // NOI18N
        additionalScrollPane.setEnabled(false);

        additionalOptionsTextArea.setColumns(20);
        additionalOptionsTextArea.setRows(5);
        additionalScrollPane.setViewportView(additionalOptionsTextArea);

        panel.add(additionalScrollPane);

        scrollPane.setViewportView(panel);

        add(scrollPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea additionalOptionsTextArea;
    private javax.swing.JScrollPane additionalScrollPane;
    private javax.swing.JPanel advanced11Panel;
    private javax.swing.JPanel advanced12Panel;
    private javax.swing.JPanel advanced1Panel;
    private javax.swing.JCheckBox backupCheckBox;
    private javax.swing.JPanel basic11Panel;
    private javax.swing.JPanel basic12Panel;
    private javax.swing.JPanel basic1Panel;
    private javax.swing.JPanel basic21Panel;
    private javax.swing.JPanel basic22Panel;
    private javax.swing.JPanel basic2Panel;
    private javax.swing.JPanel basicPanel;
    private javax.swing.JSeparator basicSeparator;
    private javax.swing.JCheckBox checksumCheckBox;
    private javax.swing.JCheckBox compressCheckBox;
    private javax.swing.JCheckBox deleteCheckBox;
    private javax.swing.JCheckBox devicesCheckBox;
    private javax.swing.JCheckBox dirsCheckBox;
    private javax.swing.JCheckBox existingCheckBox;
    private javax.swing.JCheckBox groupCheckBox;
    private javax.swing.JCheckBox hardlinksCheckBox;
    private javax.swing.JCheckBox ignoreExistingCheckBox;
    private javax.swing.JCheckBox itemizeChangesCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox linksCheckBox;
    private javax.swing.JCheckBox modifyWindowCheckBox;
    private javax.swing.JCheckBox numericIdsCheckBox;
    private javax.swing.JCheckBox oneFileSystemCheckBox;
    private javax.swing.JCheckBox ownerCheckBox;
    private javax.swing.JPanel panel;
    private javax.swing.JCheckBox partialProgressCheckBox;
    private javax.swing.JCheckBox permsCheckBox;
    private javax.swing.JCheckBox progressCheckBox;
    private javax.swing.JCheckBox protectArgsCheckBox;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JCheckBox sizeOnlyCheckBox;
    private javax.swing.JCheckBox timesCheckBox;
    private javax.swing.JCheckBox updateCheckBox;
    private javax.swing.JCheckBox verboseCheckBox;
    // End of variables declaration//GEN-END:variables
}
