/*
 * Copyright 2015 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.jotaclient.ui;

import java.util.HashMap;
import javax.swing.JTabbedPane;
import se.trixon.jota.ProcessEvent;
import se.trixon.jota.ServerEvent;
import se.trixon.jota.ServerEventListener;
import se.trixon.jota.job.Job;
import se.trixon.jota.task.Task;
import se.trixon.jotaclient.Manager;
import se.trixon.util.icon.Pict;

/**
 *
 * @author Patrik Karlsson
 */
public class ProgressPane extends JTabbedPane implements ServerEventListener {

    private SpeedDialPanel mSpeedDialPanel;
    private final HashMap<Long, ProgressPanel> mJobMap = new HashMap<>();
    private final Manager mManager = Manager.getInstance();

    /**
     * Creates new form ProgressPane
     */
    public ProgressPane() {
        initComponents();
        init();
    }

    public SpeedDialPanel getSpeedDialPanel() {
        return mSpeedDialPanel;
    }

    @Override
    public void onProcessEvent(ProcessEvent processEvent, Job job, Task task, Object object) {
        ProgressPanel panel = getPanel(job);

        if (processEvent == ProcessEvent.STARTED) {
            panel.start();
            setSelectedComponent(panel);
        } else if (processEvent == ProcessEvent.CANCELED) {
            panel.cancel();
        }
    }

    @Override
    public void onServerEvent(ServerEvent serverEvent) {
    }

    void close(Job job) {
        ProgressPanel panel = getPanel(job);
        mJobMap.remove(job.getId());
        remove(panel);
    }

    private ProgressPanel getPanel(Job job) {
        ProgressPanel panel;

        if (mJobMap.containsKey(job.getId())) {
            panel = mJobMap.get(job.getId());
        } else {
            panel = new ProgressPanel(job);
            add(panel, job.getName());
            mJobMap.put(job.getId(), panel);
            setSelectedComponent(panel);
        }

        return panel;
    }

    private void init() {
        mSpeedDialPanel = new SpeedDialPanel();
        add(mSpeedDialPanel, Pict.Actions.GO_HOME.get(UI.ICON_SIZE_LARGE));

        //mManager.addConnectionListeners(this);
        mManager.getClient().addServerEventListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
