/* 
 * Copyright 2015 Patrik Karlsson.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package se.trixon.jotaclient.ui;

import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import se.trixon.jota.job.Job;
import se.trixon.jotaclient.Manager;
import se.trixon.util.dictionary.Dict;
import se.trixon.util.icon.Pict;

/**
 *
 * @author Patrik Karlsson <patrik@trixon.se>
 */
public class ProgressPanel extends javax.swing.JPanel implements ProgressItem{
//public class ProgressPanel extends javax.swing.JPanel implements Launcher.LauncherListener {

    private Job mJob;
    private final Manager mManager = Manager.getInstance();

    /**
     * Creates new form ProgressPanel
     *
     * @param job
     */
    public ProgressPanel(Job job) {
        initComponents();
        init();
        mJob = job;
        progressBar.setValue(100);
    }

    @Override
    public JButton getMenuButton() {
        return menuButton;
    }

//    @Override
//    synchronized public void launcherLog(String string) {
//        textArea.append(string + "\n");
//    }
//
//    @Override
//    public void onLauncherFinished(int exitValue, boolean destroyedByUser) {
////        progressBar.setIndeterminate(false);
//        if (exitValue == 0) {
////            launcherLog("Finished successfully");
////            Message.information(mToolName, "Finished successfully");
//        } else if (destroyedByUser) {
////            launcherLog("Aborted by user");
////            Message.warning(mToolName, "Aborted by user");
//        } else {
////            launcherLog("Finished  with exit value=" + getErrorCode(exitValue));
////            Message.error(mToolName, String.format("Exited with: %s", getErrorCode(exitValue)));
//        }
//    }
//
//    @Override
//    synchronized public void onLauncherMessage(String message, Launcher.Mode mode) {
//        if (mode == Launcher.Mode.STD) {
//            launcherLog(message);
//        } else {
//            launcherLog("*** " + message + " ***");
//        }
//    }
    void cancel() {
        progressBar.setIndeterminate(false);
        saveButton.setEnabled(true);
        cancelButton.setVisible(false);
        closeButton.setVisible(true);
    }

    void start() {
        progressBar.setIndeterminate(true);
        //textArea.setText("");

        saveButton.setEnabled(false);
        cancelButton.setVisible(true);
        closeButton.setVisible(false);
    }

    private void init() {
        saveButton.setIcon(Pict.Actions.DOCUMENT_SAVE.get(UI.ICON_SIZE_LARGE));
        cancelButton.setIcon(Pict.Actions.PROCESS_STOP.get(UI.ICON_SIZE_LARGE));
        closeButton.setIcon(Pict.Actions.WINDOW_CLOSE.get(UI.ICON_SIZE_LARGE));
        menuButton.setIcon(Pict.Actions.FORMAT_JUSTIFY_FILL.get(UI.ICON_SIZE_LARGE));

        saveButton.setToolTipText(Dict.SAVE.getString());
        cancelButton.setToolTipText(Dict.CANCEL.getString());
        closeButton.setToolTipText(Dict.CLOSE.getString());
        menuButton.setToolTipText(Dict.MENU.getString());
    }

//    private String getErrorCode(int exitValue) {
//        String key = String.valueOf(exitValue);
//        return mExitValueBundle.containsKey(key) ? mExitValueBundle.getString(key) : String.format(("System code: %s"), key);
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        progressBar = new javax.swing.JProgressBar();
        toolBar = new javax.swing.JToolBar();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        menuButton = new javax.swing.JButton();
        logPanel = new se.trixon.util.swing.LogPanel();

        setLayout(new java.awt.GridBagLayout());

        progressBar.setIndeterminate(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(progressBar, gridBagConstraints);

        toolBar.setFloatable(false);
        toolBar.setRollover(true);

        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        toolBar.add(saveButton);

        cancelButton.setFocusable(false);
        cancelButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        toolBar.add(cancelButton);

        closeButton.setFocusable(false);
        closeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        toolBar.add(closeButton);

        menuButton.setFocusable(false);
        menuButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menuButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toolBar.add(menuButton);

        add(toolBar, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(logPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        try {
            mManager.getServerCommander().cancelJob(mJob);
        } catch (RemoteException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        ((ProgressPane) getParent()).close(mJob);
    }//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton closeButton;
    private se.trixon.util.swing.LogPanel logPanel;
    private javax.swing.JButton menuButton;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton saveButton;
    private javax.swing.JToolBar toolBar;
    // End of variables declaration//GEN-END:variables
}
